version: 2


sources:
  - name: conformed
    database: raw
    schema: conformed


    tables:
      - name: DateDimension
        columns:
          - name: DateKey
            tests:
              - unique